"""Regenerate the analytical bundle twice and compare every generated byte."""
from pathlib import Path
import hashlib
import subprocess
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "tests" / "testthat" / "fixtures" / "analytical"
GENERATOR = FIXTURES / "generate.py"


def manifest(directory, algorithm):
    result = {}
    for line in (directory / f"{algorithm.upper()}SUMS").read_text().splitlines():
        digest, name = line.split("  ", 1)
        result[name] = digest
    return result


def verify_manifest(directory, algorithm):
    expected = manifest(directory, algorithm)
    for name, digest in expected.items():
        actual = hashlib.new(algorithm, (directory / name).read_bytes()).hexdigest()
        if actual != digest:
            raise SystemExit(f"{algorithm} mismatch: {directory / name}")
    return sorted(expected)


with tempfile.TemporaryDirectory(prefix="annotatr-t12-a-") as first_temp, tempfile.TemporaryDirectory(
    prefix="annotatr-t12-b-"
) as second_temp:
    first, second = Path(first_temp), Path(second_temp)
    for output in (first, second):
        subprocess.run([sys.executable, str(GENERATOR), str(output)], check=True)

    committed_names = verify_manifest(FIXTURES, "md5")
    verify_manifest(FIXTURES, "sha256")
    for generated in (first, second):
        if verify_manifest(generated, "md5") != committed_names:
            raise SystemExit("generated file inventory differs from committed inventory")
        verify_manifest(generated, "sha256")

    compared = committed_names + ["MD5SUMS", "SHA256SUMS"]
    for name in compared:
        committed = (FIXTURES / name).read_bytes()
        if committed != (first / name).read_bytes() or committed != (second / name).read_bytes():
            raise SystemExit(f"deterministic regeneration mismatch: {name}")

print(f"analytical-reference: {len(compared)} files match committed bytes and two regenerations")
