# Accessors for the bundled synthetic example data (generated by
# data-raw/make-example-data.R).

#' Path to a bundled example file
#'
#' @param which One of `"tissue"`, `"multiplex"`, or `"cube"`.
#' @param call The calling environment, for error reporting.
#' @return A single string file path to the example asset.
#' @family example data
#' @export
#' @examples
#' at_example_path("tissue")
at_example_path <- function(which = c("tissue", "multiplex", "cube"),
                            call = rlang::caller_env()) {
  which <- .check_choice(which, c("tissue", "multiplex", "cube"), call = call)
  file <- switch(
    which,
    tissue    = "example_tissue.png",
    multiplex = "example_multiplex.tif",
    cube      = "example_cube.hdr"
  )
  system.file("extdata", file, package = "annotatR", mustWork = TRUE)
}

#' Read a bundled example image
#'
#' @param which One of `"tissue"` (RGB raster), `"multiplex"` (4-channel
#'   pyramidal TIFF), or `"cube"` (40-band ENVI spectral cube).
#' @param call The calling environment, for error reporting.
#' @return An [annot_image].
#' @family example data
#' @family images
#' @export
#' @examplesIf requireNamespace("magick", quietly = TRUE) || requireNamespace("tiff", quietly = TRUE)
#' img <- at_example_image("tissue")
#' at_dims(img)
at_example_image <- function(which = c("tissue", "multiplex", "cube"),
                             call = rlang::caller_env()) {
  which <- .check_choice(which, c("tissue", "multiplex", "cube"), call = call)
  img <- at_read_image(at_example_path(which, call = call))
  if (which == "multiplex") {
    img$band_names <- c("DAPI", "CD3", "CD8", "PanCK")
  }
  img
}

#' A populated example project
#'
#' @param call The calling environment, for error reporting.
#' @return An [annot_project] over the tissue example with one layer of three
#'   labelled regions.
#' @family example data
#' @family projects
#' @export
#' @examplesIf requireNamespace("magick", quietly = TRUE) || requireNamespace("tiff", quietly = TRUE)
#' proj <- at_example_project()
#' at_rois(proj)
at_example_project <- function(call = rlang::caller_env()) {
  img <- at_example_image("tissue", call = call)
  regions <- at_layer("regions", labels = c("tumour", "necrosis", "stroma"))
  regions <- at_layer_add(regions, at_roi_rect(120, 150, 260, 290, label = "tumour"))
  regions <- at_layer_add(regions, at_roi_rect(0, 370, 512, 512, label = "necrosis"))
  regions <- at_layer_add(regions, at_roi_rect(300, 30, 480, 220, label = "stroma"))
  at_project(img, regions, name = "example")
}

#' An example batch session
#'
#' Copies the tissue example into a temporary directory `n` times so the queue
#' has real files to iterate.
#'
#' @param n Number of images in the queue. Default `5`.
#' @param call The calling environment, for error reporting.
#' @return An [annot_session].
#' @family example data
#' @family sessions
#' @export
#' @examples
#' sess <- at_example_session(3)
#' at_session_status(sess)
at_example_session <- function(n = 5L, call = rlang::caller_env()) {
  n <- .check_count(n, min = 1L, call = call)
  src <- at_example_path("tissue", call = call)
  dir <- tempfile("annotatR-example-session-")
  dir.create(dir)
  paths <- file.path(dir, sprintf("image_%02d.png", seq_len(n)))
  for (p in paths) file.copy(src, p)
  at_session(paths, labels = c("tumour", "necrosis", "stroma"), out_dir = dir,
             call = call)
}
